// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpcdgubcprzsvmofspss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwY2RndWJjcHJ6c3Ztb2ZzcHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MjAzODMsImV4cCI6MjA1MjA5NjM4M30.nY2PhPSTB_GIdPpSc8Lu6ptR4CsXYegBgLfXrMe4-4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);